#!/usr/bin/env node
// Collects every TODO(expert-review) comment in the project into docs/EXPERT_REVIEW.md,
// grouped by module, for a qualified CNS/ATSEP engineer to check.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = join(import.meta.dirname, '..')
const scan = ['src', 'docs'].map((d) => join(root, d))
const exts = /\.(ts|tsx|mdx|md|json)$/

const MODULE_NAMES = {
  core: 'Shared simulation core',
  psr: 'Primary Surveillance Radar (PSR)',
  radar: 'Primary Surveillance Radar (PSR)',
  ssr: 'Secondary Surveillance Radar and Mode S',
  ads: 'ADS-B and ADS-C',
  mlat: 'MLAT and WAM',
  surface: 'Surface Movement Radar and A-SMGCS',
  ndb: 'NDB and ADF',
  dvor: 'CVOR and DVOR',
  vor: 'CVOR and DVOR',
  dme: 'DME',
  ils: 'ILS',
  gnss: 'GNSS, SBAS and GBAS',
  vhf: 'VHF/UHF radio',
  hf: 'HF radio',
  cpdlc: 'CPDLC',
  satcom: 'SATCOM',
  sandbox: 'Airspace Sandbox',
  fusion: 'Airspace Sandbox',
  safetyNets: 'Airspace Sandbox',
  content: 'Shared content (frequency chart, glossary)',
}

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p, out)
    else if (exts.test(name) && !p.endsWith('EXPERT_REVIEW.md') && !p.endsWith('MODULE_AUTHORING.md') && !p.includes('ATM_Simulation_Development_Guide')) out.push(p)
  }
  return out
}

function groupOf(rel) {
  let m = rel.match(/src\/modules\/([^/]+)\//)
  if (m) return m[1]
  m = rel.match(/src\/core\/([^/.]+)\./)
  if (m) return MODULE_NAMES[m[1]] ? m[1] : 'core'
  if (rel.includes('src/pages/Sandbox')) return 'sandbox'
  if (rel.includes('src/content')) return 'content'
  return 'core'
}

const groups = new Map()
for (const file of scan.flatMap((d) => walk(d))) {
  const rel = relative(root, file)
  const lines = readFileSync(file, 'utf8').split('\n')
  lines.forEach((line, i) => {
    const m = line.match(/TODO\(expert-review\):?\s*(.*?)(\*\/\}?|-->)?\s*$/)
    if (!m) return
    const text = m[1].replace(/\*\/\s*\}?$/, '').trim() || '(see code)'
    const key = MODULE_NAMES[groupOf(rel)] ?? groupOf(rel)
    if (!groups.has(key)) groups.set(key, [])
    groups.get(key).push({ rel, line: i + 1, text })
  })
}

const order = [...new Set(Object.values(MODULE_NAMES))]
const keys = [...groups.keys()].sort((a, b) => order.indexOf(a) - order.indexOf(b))
let md = `# Expert review list\n\nEvery value in CNS Lab that a qualified CNS/ATSEP engineer should check against ICAO Annex 10 (Volumes I–IV), the relevant ICAO manuals and local ANSP documentation. Generated by \`npm run expert-review\` from the \`TODO(expert-review)\` comments in the code; do not edit by hand.\n\nTotal items: ${[...groups.values()].reduce((n, g) => n + g.length, 0)}\n`
for (const k of keys) {
  md += `\n## ${k}\n\n| Item | Where |\n|---|---|\n`
  for (const it of groups.get(k)) md += `| ${it.text.replace(/\|/g, '\\|')} | \`${it.rel}:${it.line}\` |\n`
}
md += `\n---\n\nSign-off: ____________________ (name, licence/qualification, date)\n`
writeFileSync(join(root, 'docs/EXPERT_REVIEW.md'), md)
console.log(`Wrote docs/EXPERT_REVIEW.md with ${[...groups.values()].reduce((n, g) => n + g.length, 0)} items in ${keys.length} groups.`)
